etc/poem.ini, poem.spec, poem/Poem/manage.py, poem/Poem/poem/management/__init__.py, poem/Poem/poem/templates/hints_metrics, poem/Poem/poem/views.py, poem/Poem/settings.py, poem/Poem/sync/poem-syncservtype.py, poem/Poem/urls_api.py
- added forgotten completion for metrics
- SRMv2 service type is now manually added in syncservtype
- update deprecated manage.py django project setter
- automate superuser creation: createdb tool doesn't need to be interactive anymore
https://github.com/ARGOeu/poem/issues/9
=> few updates and fixes

bin/poem-createdb, bin/poem-syncservtype, bin/poem-syncvo, etc/poem_logging.ini, poem.spec, poem/Poem/poem/admin.py, poem/Poem/poem/management/commands/import_profiles.py, poem/Poem/poem/management/update_profile.py, poem/Poem/poem/templates/profiles, poem/Poem/poem/views.py, poem/Poem/settings.py, poem/Poem/sync/poem-syncservtype.py, poem/Poem/sync/poem-syncvo.py
- consistent service flavour name field with old profiles API 
https://github.com/ARGOeu/ARGO/issues/151
- remove DN owner field from profiles API 
- scripts should complain about any argument passed
https://github.com/ARGOeu/ARGO/issues/150
- minor render changes in group-profiles widget
- sync tools report via syslog
https://github.com/ARGOeu/ARGO/issues/152
=> bugfixes for script args and profiles API, improved logging

poem.spec, poem/Poem/poem/admin.py, poem/Poem/poem/management/update_profile.py, poem/Poem/ssl_auth/backends.py
- fix column uniqueness error while syncing service types
https://github.com/ARGOeu/ARGO/issues/177
- catch failed DB operations
- import profiles over https
https://github.com/ARGOeu/ARGO/issues/176
=> bugfix and some minor improvements

poem.spec, poem/Poem/sync/poem-syncservtype.py, poem/Poem/sync/poem-syncvo.py, setup.py
=> ARGO-613 Timeout in sync scripts

poem.spec, poem/Poem/poem/admin_interface/siteprofile.py, poem/Poem/poem/dbmodels/profiles.py
- fixed group membership of newly created profiles
- add missing copy module in group of profiles association code
/please review @themiszamani
=> ARGO-641 fixed group membership of newly created profiles

poem.spec, poem/Poem/sync/poem-syncservtype.py
=> ARGO-766 remove manual insertion of SRMv2 service type

etc/poem.ini, poem/Poem/settings.py
added obligatory ALLOWED_HOSTS settings
=> ARGO-834 POEM breaks with python-django-1.6.11.6-1.el7

poem/Poem/poem/admin_interface/sitemetrics.py
=> ARGO-878  Metric can end up wrongly associated to probe revision

poem/Poem/poem/admin_interface/siteprobes.py, poem/Poem/poem/templates/reversion/poem/probe/revision_form.html
=> ARGO-885 Probe create revision datetime is wrongly presented in UI

bin/poem-db, cron/poem-clearsessions, poem.spec, setup.py
- cronjob that clears expired login sessions from DB
=> ARGO-939 Automatic purge of expired sessions

bin/poem-genseckey, poem.spec, poem/Poem/settings.py, setup.py
* introduced tool that creates secure SECRET_KEY and write it into file
* POEM configuration expect it to have in /etc/poem/secret_key
=> ARGO-937 Use private SECRET_KEY

etc/poem.conf, poem/Poem/settings.py
* SECRET_KEY file path in main config
=>  ARGO-937 Use private SECRET_KEY 

Makefile, poem.spec, poem/Poem/poem/templates/reversion/poem/metric/compare.html, poem/Poem/poem/templates/reversion/poem/metric/revision_form.html
added slipped revision metric template
spec update for prod release fix
revision templates with proper breadcumb
=> Merge for v1.1.0-2

poem/Poem/poem/admin_interface/sitemetrics.py, poem/Poem/poem/templates/admin/edit_inline/tabular-attrs.html, poem/media/css/sitemetrics.css
Five Metric Config attribute keys are shown as default in MetricAddForm. The button to add another Config is removed.
=> ARGO-1309 Static Metric Config attribute with predefined keys

poem/Poem/poem/admin_interface/sitemetrics.py, poem/Poem/poem/templates/reversion/poem/metric/revision_form.html
* applied the same inline logic for adminform as well
=> ARGO-950 Metric history browse always show most recent changes

poem/Poem/poem/templates/admin/poem/metric/object_history.html, poem/Poem/poem/templatetags/plaintext_comments.py
Fixed a bug with rendering comments in history view.
=> ARGO-1568 History comments not rendered properly

poem/Poem/api/tests/test_views_internal.py, poem/Poem/api/urls_internal.py, poem/Poem/api/views_internal.py, poem/Poem/poem/admin.py, poem/Poem/poem/admin_interface/siteactions.py, poem/Poem/poem/templates/admin/admin/logentry/change_form.html, poem/Poem/poem/templates/admin/admin/logentry/change_form_object_tools.html, poem/Poem/poem/templates/admin/admin/logentry/change_list.html, poem/Poem/poem/templates/admin/index.html, poem/media/css/siteactions.css
Superusers will be able to see recent actions in admin panel.
=> ARGO-1449 Add ability to browse all recent actions in POEM for superusers

poem/Poem/api/tests/test_views.py, poem/Poem/poem/tests/test_apiv1.py
A few changes in the code for testing without db.
=> ARGO-1612 Fix tests by creating all needed tables in in-memory-DB

testenv/Dockerfile, testenv/setup_test.sh
* refined build of test env that requires cloned source dir passed as argument
=> ARGO-1580 Minimal container for tests

poem/Poem/poem/admin_interface/siteactions.py, poem/Poem/poem/templates/admin/admin/logentry/change_form.html, poem/Poem/poem/templates/admin/admin/logentry/change_list.html, poem/Poem/poem/templatetags/logentry_breadcrumb.py
In log entry change view only one sentence description is listed, detailed description is available in view for every log entry, along with some other information.
=> ARGO-1628 Refine log entries view
